services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ai_task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: "postgresql://postgres:postgresql123@database:5432/ai_task_manager"
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy
    command: sh -c "npx prisma db push && npm start"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      NEXT_PUBLIC_API_URL: http://server:5000/api
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  postgres_data: